apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnnycash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: johnnycash
  template:
    metadata:
      labels:
        app: johnnycash
        version: v0.15
    spec:
      containers:
      - name: johnnycash
        image: toolboc/johnnycash
        ports:
        - containerPort: 9666
          name: johnnycash
          protocol: TCP